Fix #4
sttz/trimmer pull request #5
Opened 2020-01-24 04:22 UTC by JesseTG

2020-01-24 04:27 UTC, JesseTG commented
Wait, no, I think I found a simpler way.

2020-01-25 10:38 UTC, sttz requested changes
Great, thanks for the PR!

Looks good overall. Try to keep whitespace changes to a minimum and put them in a separate commit, makes reviewing much easier.

2020-01-25 10:38 UTC, sttz commented on Editor/BuildManager.cs
>          string result;
You can remove this variable now since it's no longer used

2020-01-25 10:38 UTC, sttz commented on Editor/BuildManager.cs
> +        finally {
Put the braces and the finally on the same line: "} finally {"

2020-01-25 21:38 UTC, JesseTG commented
Ah, it's not ready yet. I gotta test this locally first.

2021-06-24 20:30 UTC, closed without merging